##
# Configuration File of teclp v1.22
# Author: wallnuss
# Please use no tabs instead use spaces for indentation.
##

##
# tectonicusDirectory:
# If you want to customize the storage of your data change that.
# Please notice that you will need to point tectonicus to that Directory manually.
# tectonicusDirectory = 'plugins/teclp/data/'
##

##
# port:
# If you want to use an other port.
# port: 5555
##

##
# debug:
# If you experience any problems activate the debug flag.
# debug: true
##
debug: false